/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'coin_identification';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String COINA = 'assets/Images/coina.png';
  static const String COINAAA = 'assets/Images/coinaaa.png';
  static const String COINB = 'assets/Images/coinb.png';
}
